// Code generated by goenums v0.5.0; DO NOT EDIT.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f -i operation.go

package insensitive

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"
	"strings"

	"golang.org/x/exp/constraints"
)

// OperationType is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type OperationType struct {
	operationType
	Active bool
}

// operationTypesContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the OperationType type.
type operationTypesContainer struct {
	UPDATE OperationType
	REMOVE OperationType
}

// OperationTypes is a main entry point using the OperationType type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var OperationTypes = operationTypesContainer{
	UPDATE: OperationType{
		operationType: update,
		Active:        true,
	},
	REMOVE: OperationType{
		operationType: remove,
		Active:        false,
	},
}

// invalidOperationType is an invalid sentinel value for OperationType
var invalidOperationType = OperationType{
	operationType: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o operationTypesContainer) allSlice() []OperationType {
	return []OperationType{
		OperationTypes.UPDATE,
		OperationTypes.REMOVE,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o operationTypesContainer) All() iter.Seq[OperationType] {
	return func(yield func(OperationType) bool) {
		for _, v := range o.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseOperationType = errors.New("invalid input provided to parse to OperationType")

// ParseOperationType parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseOperationType(input any) (OperationType, error) {
	switch v := input.(type) {
	case OperationType:
		return v, nil
	case string:
		if result := stringToOperationType(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToOperationType(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToOperationType(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToOperationType(v); result != nil {
			return *result, nil
		}
	default:
		return invalidOperationType, fmt.Errorf("invalid type %T", input)
	}
	return invalidOperationType, fmt.Errorf("%w: invalid value %v", ErrParseOperationType, input)
}

// operationTypesNameMap is a map of enum values to their OperationType representation
// It is used to convert string representations of enum values into their OperationType representation.
var operationTypesNameMap = map[string]OperationType{
	"update": OperationTypes.UPDATE,
	"remove": OperationTypes.REMOVE,
}

// stringToOperationType converts a string representation of an enum value into its OperationType representation
// It returns a pointer to the OperationType representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToOperationType(s string) *OperationType {
	s = strings.ToLower(s)
	if t, ok := operationTypesNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToOperationType converts a numeric value to a OperationType
// It returns a pointer to the OperationType representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToOperationType[T constraints.Integer | constraints.Float](num T) *OperationType {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(OperationTypes.allSlice()) {
		return nil
	}
	result := OperationTypes.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveOperationTypes iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveOperationTypes(f func(OperationType)) {
	for _, p := range OperationTypes.allSlice() {
		f(p)
	}
}

type OperationTypeMatcher interface {
	Update()
	Remove()
}

// MatchOperationType dispatches to the matcher method for the given enum value.
// The OperationTypeMatcher interface provides compile-time exhaustiveness: when enum
// values are added, removed, or renamed, existing matcher implementations stop
// satisfying this interface until they are updated.
func MatchOperationType(en OperationType, matcher OperationTypeMatcher) error {
	if matcher == nil {
		return fmt.Errorf("nil OperationTypeMatcher")
	}
	switch en {
	case OperationTypes.UPDATE:
		matcher.Update()
	case OperationTypes.REMOVE:
		matcher.Remove()
	default:
		return fmt.Errorf("unhandled OperationType: %v", en)
	}
	return nil
}

// MustMatchOperationType dispatches to the matcher method for the given enum value.
// It panics if matcher is nil or the enum value is not handled.
func MustMatchOperationType(en OperationType, matcher OperationTypeMatcher) {
	if err := MatchOperationType(en, matcher); err != nil {
		panic(err)
	}
}

// validOperationTypes is a map of enum values to their validity
var validOperationTypes = map[OperationType]bool{
	OperationTypes.UPDATE: true,
	OperationTypes.REMOVE: true,
}

// IsValid checks whether the OperationTypes value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (o OperationType) IsValid() bool {
	return validOperationTypes[o]
}

// MarshalJSON implements the json.Marshaler interface for OperationType.
// It returns the JSON representation of the enum value as a byte slice.
func (o OperationType) MarshalJSON() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for OperationType.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (o *OperationType) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newo, err := ParseOperationType(by)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for OperationType.
// It returns the string representation of the enum value as a byte slice
func (o OperationType) MarshalText() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for OperationType.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *OperationType) UnmarshalText(by []byte) error {
	newo, err := ParseOperationType(by)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Scan implements the database/sql.Scanner interface for OperationType.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (o *OperationType) Scan(value any) error {
	newo, err := ParseOperationType(value)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Value implements the database/sql/driver.Valuer interface for OperationType.
// It returns the string representation of the enum value.
func (o OperationType) Value() (driver.Value, error) {
	return o.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for OperationType.
// It returns the binary representation of the enum value as a byte slice.
func (o OperationType) MarshalBinary() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for OperationType.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *OperationType) UnmarshalBinary(by []byte) error {
	newo, err := ParseOperationType(by)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for OperationType.
// It returns the string representation of the enum value.
func (o OperationType) MarshalYAML() ([]byte, error) {
	return []byte(o.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (o *OperationType) UnmarshalYAML(by []byte) error {
	newo, err := ParseOperationType(by)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// operationtypeNames is a constant string slice containing all enum values cononical absolute names
const operationtypeNames = "updateremove"

// operationtypeNamesMap is a map of enum values to their canonical absolute
// name positions within the operationtypeNames string slice
var operationtypeNamesMap = map[OperationType]string{
	OperationTypes.UPDATE: operationtypeNames[0:6],
	OperationTypes.REMOVE: operationtypeNames[6:12],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (o OperationType) String() string {
	if str, ok := operationtypeNamesMap[o]; ok {
		return str
	}
	return fmt.Sprintf("operationtype(%d)", o.operationType)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [3]struct{}
	_ = x[update-1]
	_ = x[remove-2]
}
