// Code generated by goenums v0.3.6. DO NOT EDIT.
// This file was generated by github.com/zarldev/goenums
// using the command:
// goenums testdata/sale/discount.go

package sale

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"strconv"
	"time"
)

type DiscountType struct {
	discountType
	Available bool
	Started   bool
	Finished  bool
	Cancelled bool
	Duration  time.Duration
}

type discounttypesContainer struct {
	SALE       DiscountType
	PERCENTAGE DiscountType
	AMOUNT     DiscountType
	GIVEAWAY   DiscountType
}

var DiscountTypes = discounttypesContainer{
	SALE: DiscountType{
		discountType: sale,
		Available:    0,
		Started:      1,
		Finished:     2,
		Cancelled:    3,
		Duration:     4,
	},
	PERCENTAGE: DiscountType{
		discountType: percentage,
		Available:    0,
		Started:      1,
		Finished:     2,
		Cancelled:    3,
		Duration:     4,
	},
	AMOUNT: DiscountType{
		discountType: amount,
		Available:    0,
		Started:      1,
		Finished:     2,
		Cancelled:    3,
		Duration:     4,
	},
	GIVEAWAY: DiscountType{
		discountType: giveaway,
		Available:    0,
		Started:      1,
		Finished:     2,
		Cancelled:    3,
		Duration:     4,
	},
}

var invalidDiscountType = DiscountType{}

func (c discounttypesContainer) allSlice() []DiscountType {
	return []DiscountType{
		c.SALE,
		c.PERCENTAGE,
		c.AMOUNT,
		c.GIVEAWAY,
	}
}

// AllSlice returns all valid DiscountType values as a slice.
// Deprecated: Use All() with Go 1.23+ range over function types instead.
func (c discounttypesContainer) AllSlice() []DiscountType {
	return c.allSlice()
}

// All returns all valid DiscountType values.
func (c discounttypesContainer) All() iter.Seq[DiscountType] {
	return func(yield func(DiscountType) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

func ParseDiscountType(a any) (DiscountType, error) {
	res := invalidDiscountType
	switch v := a.(type) {
	case DiscountType:
		return v, nil
	case []byte:
		res = stringToDiscountType(string(v))
	case string:
		res = stringToDiscountType(v)
	case fmt.Stringer:
		res = stringToDiscountType(v.String())
	case int:
		res = intToDiscountType(v)
	case int64:
		res = intToDiscountType(int(v))
	case int32:
		res = intToDiscountType(int(v))
	}
	return res, nil
}

var (
	_discounttypesNameMap = map[string]DiscountType{
		"sale":       DiscountTypes.SALE,
		"percentage": DiscountTypes.PERCENTAGE,
		"amount":     DiscountTypes.AMOUNT,
		"giveaway":   DiscountTypes.GIVEAWAY,
	}
)

func stringToDiscountType(s string) DiscountType {
	if v, ok := _discounttypesNameMap[s]; ok {
		return v
	}
	return invalidDiscountType
}

func intToDiscountType(i int) DiscountType {
	i = i - 1
	if i < 0 || i >= len(DiscountTypes.allSlice()) {
		return invalidDiscountType
	}
	return DiscountTypes.allSlice()[i]
}

func ExhaustiveDiscountTypes(f func(DiscountType)) {
	for _, p := range DiscountTypes.allSlice() {
		f(p)
	}
}

var validDiscountTypes = map[DiscountType]bool{
	DiscountTypes.SALE:       true,
	DiscountTypes.PERCENTAGE: true,
	DiscountTypes.AMOUNT:     true,
	DiscountTypes.GIVEAWAY:   true,
}

func (p DiscountType) IsValid() bool {
	return validDiscountTypes[p]
}

func (p DiscountType) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *DiscountType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, `"`), ` `)
	newp, err := ParseDiscountType(b)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p *DiscountType) Scan(value any) error {
	newp, err := ParseDiscountType(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p DiscountType) Value() (driver.Value, error) {
	return p.String(), nil
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [1]struct{}
	_ = x[sale-1]
	_ = x[percentage-2]
	_ = x[amount-3]
	_ = x[giveaway-4]
}

const _discounttypes_name = "salepercentageamountgiveaway"

var _discounttypes_index = [...]uint16{0, 0, 4, 14, 20, 28}

func (i discountType) String() string {
	if i < 1 || i >= discountType(len(_discounttypes_index)-1) {
		return "discounttypes(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _discounttypes_name[_discounttypes_index[i]:_discounttypes_index[i+1]]
}
