// Code generated by goenums v0.3.6 at 2025-04-17T20:21:33+01:00. DO NOT EDIT.
// This file was generated by github.com/zarldev/goenums
// using the command:
// goenums ../internal/testdata/sale/discount.go

package sale

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"strconv"
	"time"
)

type Discounttype struct {
	discountType
	Available bool
	Started   bool
	Finished  bool
	Cancelled bool
	Duration  time.Duration
}

type discounttypesContainer struct {
	SALE       Discounttype
	PERCENTAGE Discounttype
	AMOUNT     Discounttype
	GIVEAWAY   Discounttype
}

var Discounttypes = discounttypesContainer{
	SALE: Discounttype{
		discountType: sale,
		Available:    false,
		Started:      true,
		Finished:     true,
		Cancelled:    false,
		Duration:     "24*7*time.Hour",
	},
	PERCENTAGE: Discounttype{
		discountType: percentage,
		Available:    false,
		Started:      false,
		Finished:     false,
		Cancelled:    false,
		Duration:     "24*time.Hour",
	},
	AMOUNT: Discounttype{
		discountType: amount,
		Available:    false,
		Started:      false,
		Finished:     false,
		Cancelled:    false,
		Duration:     "48*time.Hour",
	},
	GIVEAWAY: Discounttype{
		discountType: giveaway,
		Available:    true,
		Started:      true,
		Finished:     false,
		Cancelled:    false,
		Duration:     "72*time.Hour",
	},
}

var invalidDiscounttype = Discounttype{}

func (c discounttypesContainer) allSlice() []Discounttype {
	return []Discounttype{
		c.SALE,
		c.PERCENTAGE,
		c.AMOUNT,
		c.GIVEAWAY,
	}
}

// AllSlice returns all valid Discounttype values as a slice.
// Deprecated: Use All() with Go 1.23+ range over function types instead.
func (c discounttypesContainer) AllSlice() []Discounttype {
	return c.allSlice()
}

// All returns all valid Discounttype values.
func (c discounttypesContainer) All() iter.Seq[Discounttype] {
	return func(yield func(Discounttype) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

func ParseDiscounttype(a any) (Discounttype, error) {
	res := invalidDiscounttype
	switch v := a.(type) {
	case Discounttype:
		return v, nil
	case []byte:
		res = stringToDiscounttype(string(v))
	case string:
		res = stringToDiscounttype(v)
	case fmt.Stringer:
		res = stringToDiscounttype(v.String())
	case int:
		res = intToDiscounttype(v)
	case int64:
		res = intToDiscounttype(int(v))
	case int32:
		res = intToDiscounttype(int(v))
	}
	return res, nil
}

var (
	_discounttypesNameMap = map[string]Discounttype{
		"sale":       Discounttypes.SALE,
		"percentage": Discounttypes.PERCENTAGE,
		"amount":     Discounttypes.AMOUNT,
		"giveaway":   Discounttypes.GIVEAWAY,
	}
)

func stringToDiscounttype(s string) Discounttype {
	if v, ok := _discounttypesNameMap[s]; ok {
		return v
	}
	return invalidDiscounttype
}

func intToDiscounttype(i int) Discounttype {
	i = i - 1
	if i < 0 || i >= len(Discounttypes.allSlice()) {
		return invalidDiscounttype
	}
	return Discounttypes.allSlice()[i]
}

func ExhaustiveDiscounttypes(f func(Discounttype)) {
	for _, p := range Discounttypes.allSlice() {
		f(p)
	}
}

var validDiscounttypes = map[Discounttype]bool{
	Discounttypes.SALE:       true,
	Discounttypes.PERCENTAGE: true,
	Discounttypes.AMOUNT:     true,
	Discounttypes.GIVEAWAY:   true,
}

func (p Discounttype) IsValid() bool {
	return validDiscounttypes[p]
}

func (p Discounttype) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *Discounttype) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, `"`), ` `)
	newp, err := ParseDiscounttype(b)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p *Discounttype) Scan(value any) error {
	newp, err := ParseDiscounttype(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p Discounttype) Value() (driver.Value, error) {
	return p.String(), nil
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [1]struct{}
	_ = x[sale-1]
	_ = x[percentage-2]
	_ = x[amount-3]
	_ = x[giveaway-4]
}

const _discounttypes_name = "salepercentageamountgiveaway"

var _discounttypes_index = [...]uint16{0, 0, 4, 14, 20, 28}

func (i discountType) String() string {
	if i < 1 || i >= discountType(len(_discounttypes_index)-1) {
		return "discounttypes(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _discounttypes_name[_discounttypes_index[i]:_discounttypes_index[i+1]]
}
