// Code generated by goenums v0.3.6 at 2025-04-17T15:57:27+01:00. DO NOT EDIT.
// This file was generated by github.com/zarldev/goenums
// using the command:
// goenums testdata/spaces/tickets.go

package spaces

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"strconv"
)

type Ticketstatus struct {
	ticketStatus
}

type ticketstatusesContainer struct {
	UNKNOWN   Ticketstatus
	PENDING   Ticketstatus
	APPROVED  Ticketstatus
	REJECTED  Ticketstatus
	COMPLETED Ticketstatus
}

var Ticketstatuses = ticketstatusesContainer{
	PENDING: Ticketstatus{
		ticketStatus: pending,
	},
	APPROVED: Ticketstatus{
		ticketStatus: approved,
	},
	REJECTED: Ticketstatus{
		ticketStatus: rejected,
	},
	COMPLETED: Ticketstatus{
		ticketStatus: completed,
	},
}

var invalidTicketstatus = Ticketstatus{}

func (c ticketstatusesContainer) allSlice() []Ticketstatus {
	return []Ticketstatus{
		c.PENDING,
		c.APPROVED,
		c.REJECTED,
		c.COMPLETED,
	}
}

// AllSlice returns all valid Ticketstatus values as a slice.
// Deprecated: Use All() with Go 1.23+ range over function types instead.
func (c ticketstatusesContainer) AllSlice() []Ticketstatus {
	return c.allSlice()
}

// All returns all valid Ticketstatus values.
func (c ticketstatusesContainer) All() iter.Seq[Ticketstatus] {
	return func(yield func(Ticketstatus) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

func ParseTicketstatus(a any) (Ticketstatus, error) {
	res := invalidTicketstatus
	switch v := a.(type) {
	case Ticketstatus:
		return v, nil
	case []byte:
		res = stringToTicketstatus(string(v))
	case string:
		res = stringToTicketstatus(v)
	case fmt.Stringer:
		res = stringToTicketstatus(v.String())
	case int:
		res = intToTicketstatus(v)
	case int64:
		res = intToTicketstatus(int(v))
	case int32:
		res = intToTicketstatus(int(v))
	}
	return res, nil
}

var (
	_ticketstatusesNameMap = map[string]Ticketstatus{
		"unknown":                Ticketstatuses.UNKNOWN,
		"In Progress":            Ticketstatuses.PENDING,
		"Fully Approved":         Ticketstatuses.APPROVED,
		"Has Been Rejected":      Ticketstatuses.REJECTED,
		"Successfully Completed": Ticketstatuses.COMPLETED,
	}
)

func stringToTicketstatus(s string) Ticketstatus {
	if v, ok := _ticketstatusesNameMap[s]; ok {
		return v
	}
	return invalidTicketstatus
}

func intToTicketstatus(i int) Ticketstatus {
	if i < 0 || i >= len(Ticketstatuses.allSlice()) {
		return invalidTicketstatus
	}
	return Ticketstatuses.allSlice()[i]
}

func ExhaustiveTicketstatuss(f func(Ticketstatus)) {
	for _, p := range Ticketstatuses.allSlice() {
		f(p)
	}
}

var validTicketstatuses = map[Ticketstatus]bool{
	Ticketstatuses.PENDING:   true,
	Ticketstatuses.APPROVED:  true,
	Ticketstatuses.REJECTED:  true,
	Ticketstatuses.COMPLETED: true,
}

func (p Ticketstatus) IsValid() bool {
	return validTicketstatuses[p]
}

func (p Ticketstatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *Ticketstatus) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, `"`), ` `)
	newp, err := ParseTicketstatus(b)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p *Ticketstatus) Scan(value any) error {
	newp, err := ParseTicketstatus(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p Ticketstatus) Value() (driver.Value, error) {
	return p.String(), nil
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[pending-1]
	_ = x[approved-2]
	_ = x[rejected-3]
	_ = x[completed-4]
}

const _ticketstatuses_name = "unknownIn ProgressFully ApprovedHas Been RejectedSuccessfully Completed"

var _ticketstatuses_index = [...]uint16{0, 7, 18, 32, 49, 71}

func (i ticketStatus) String() string {
	if i < 0 || i >= ticketStatus(len(_ticketstatuses_index)-1) {
		return "ticketstatuses(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _ticketstatuses_name[_ticketstatuses_index[i]:_ticketstatuses_index[i+1]]
}
