// DO NOT EDIT.
// code generated by goenums 'v0.4.2' at Jun 30 01:30:48.
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f multiple.go

package multipleenums

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// Order is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type Order struct {
	order
}

// ordersContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the Order type.
type ordersContainer struct {
	CREATED     Order
	APPROVED    Order
	PROCESSING  Order
	READYTOSHIP Order
	SHIPPED     Order
	DELIVERED   Order
	CANCELLED   Order
}

// Orders is a main entry point using the Order type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var Orders = ordersContainer{
	CREATED: Order{
		order: created,
	},
	APPROVED: Order{
		order: approved,
	},
	PROCESSING: Order{
		order: processing,
	},
	READYTOSHIP: Order{
		order: readyToShip,
	},
	SHIPPED: Order{
		order: shipped,
	},
	DELIVERED: Order{
		order: delivered,
	},
	CANCELLED: Order{
		order: cancelled,
	},
}

// invalidOrder is an invalid sentinel value for Order
var invalidOrder = Order{
	order: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o ordersContainer) allSlice() []Order {
	return []Order{
		Orders.CREATED,
		Orders.APPROVED,
		Orders.PROCESSING,
		Orders.READYTOSHIP,
		Orders.SHIPPED,
		Orders.DELIVERED,
		Orders.CANCELLED,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (o ordersContainer) All() iter.Seq[Order] {
	return func(yield func(Order) bool) {
		for _, v := range o.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseOrder = errors.New("invalid input provided to parse to Order")

// ParseOrder parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseOrder(input any) (Order, error) {
	switch v := input.(type) {
	case Order:
		return v, nil
	case string:
		if result := stringToOrder(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToOrder(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToOrder(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToOrder(v); result != nil {
			return *result, nil
		}
	default:
		return invalidOrder, fmt.Errorf("invalid type %T", input)
	}
	return invalidOrder, fmt.Errorf("%w: invalid value %v", ErrParseOrder, input)
}

// ordersNameMap is a map of enum values to their Order representation
// It is used to convert string representations of enum values into their Order representation.
var ordersNameMap = map[string]Order{
	"CREATED":       Orders.CREATED,
	"APPROVED":      Orders.APPROVED,
	"PROCESSING":    Orders.PROCESSING,
	"READY_TO_SHIP": Orders.READYTOSHIP,
	"SHIPPED":       Orders.SHIPPED,
	"DELIVERED":     Orders.DELIVERED,
	"CANCELLED":     Orders.CANCELLED,
}

// stringToOrder converts a string representation of an enum value into its Order representation
// It returns a pointer to the Order representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToOrder(s string) *Order {
	if t, ok := ordersNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToOrder converts a numeric value to a Order
// It returns a pointer to the Order representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToOrder[T constraints.Integer | constraints.Float](num T) *Order {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(Orders.allSlice()) {
		return nil
	}
	result := Orders.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveOrders iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveOrders(f func(Order)) {
	for _, p := range Orders.allSlice() {
		f(p)
	}
}

// validOrders is a map of enum values to their validity
var validOrders = map[Order]bool{
	Orders.CREATED:     true,
	Orders.APPROVED:    true,
	Orders.PROCESSING:  true,
	Orders.READYTOSHIP: true,
	Orders.SHIPPED:     true,
	Orders.DELIVERED:   true,
	Orders.CANCELLED:   true,
}

// IsValid checks whether the Orders value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (o Order) IsValid() bool {
	return validOrders[o]
}

// MarshalJSON implements the json.Marshaler interface for Order.
// It returns the JSON representation of the enum value as a byte slice.
func (o Order) MarshalJSON() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for Order.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (o *Order) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, "\""), "\"")
	newo, err := ParseOrder(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for Order.
// It returns the string representation of the enum value as a byte slice
func (o Order) MarshalText() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Order.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *Order) UnmarshalText(b []byte) error {
	newo, err := ParseOrder(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Scan implements the database/sql.Scanner interface for Order.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (o *Order) Scan(value any) error {
	newo, err := ParseOrder(value)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// Value implements the database/sql/driver.Valuer interface for Order.
// It returns the string representation of the enum value.
func (o Order) Value() (driver.Value, error) {
	return o.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Order.
// It returns the binary representation of the enum value as a byte slice.
func (o Order) MarshalBinary() ([]byte, error) {
	return []byte("\"" + o.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Order.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (o *Order) UnmarshalBinary(b []byte) error {
	newo, err := ParseOrder(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for Order.
// It returns the string representation of the enum value.
func (o Order) MarshalYAML() ([]byte, error) {
	return []byte(o.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (o *Order) UnmarshalYAML(b []byte) error {
	newo, err := ParseOrder(b)
	if err != nil {
		return err
	}
	*o = newo
	return nil
}

// orderNames is a constant string slice containing all enum values cononical absolute names
const orderNames = "CREATEDAPPROVEDPROCESSINGREADY_TO_SHIPSHIPPEDDELIVEREDCANCELLED"

// orderNamesMap is a map of enum values to their canonical absolute
// name positions within the orderNames string slice
var orderNamesMap = map[Order]string{
	Orders.CREATED:     orderNames[0:7],
	Orders.APPROVED:    orderNames[7:15],
	Orders.PROCESSING:  orderNames[15:25],
	Orders.READYTOSHIP: orderNames[25:38],
	Orders.SHIPPED:     orderNames[38:45],
	Orders.DELIVERED:   orderNames[45:54],
	Orders.CANCELLED:   orderNames[54:63],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (o Order) String() string {
	if str, ok := orderNamesMap[o]; ok {
		return str
	}
	return fmt.Sprintf("order(%d)", o.order)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [7]struct{}
	_ = x[created]
	_ = x[approved-1]
	_ = x[processing-2]
	_ = x[readyToShip-3]
	_ = x[shipped-4]
	_ = x[delivered-5]
	_ = x[cancelled-6]
}
