// Code generated by goenums. DO NOT EDIT.
// This file was generated by github.com/zarldev/goenums
// using the command:
// goenums -f discount.go

package sale

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"strconv"
)

type DiscountType struct {
	discountType
}

type discounttypesContainer struct {
	SALE       DiscountType
	PERCENTAGE DiscountType
	AMOUNT     DiscountType
	GIVEAWAY   DiscountType
}

var DiscountTypes = discounttypesContainer{
	SALE: DiscountType{
		discountType: sale,
	},
	PERCENTAGE: DiscountType{
		discountType: percentage,
	},
	AMOUNT: DiscountType{
		discountType: amount,
	},
	GIVEAWAY: DiscountType{
		discountType: giveaway,
	},
}

func (c discounttypesContainer) All() []DiscountType {
	return []DiscountType{
		c.SALE,
		c.PERCENTAGE,
		c.AMOUNT,
		c.GIVEAWAY,
	}
}

var invalidDiscountType = DiscountType{}

func ParseDiscountType(a any) (DiscountType, error) {
	res := invalidDiscountType
	switch v := a.(type) {
	case DiscountType:
		return v, nil
	case []byte:
		res = stringToDiscountType(string(v))
	case string:
		res = stringToDiscountType(v)
	case fmt.Stringer:
		res = stringToDiscountType(v.String())
	case int:
		res = intToDiscountType(v)
	case int64:
		res = intToDiscountType(int(v))
	case int32:
		res = intToDiscountType(int(v))
	}
	if res == invalidDiscountType {
		return res, fmt.Errorf("failed to parse %v", a)
	}
	return res, nil
}

func stringToDiscountType(s string) DiscountType {
	switch s {
	case "sale":
		return DiscountTypes.SALE
	case "percentage":
		return DiscountTypes.PERCENTAGE
	case "amount":
		return DiscountTypes.AMOUNT
	case "giveaway":
		return DiscountTypes.GIVEAWAY
	}
	return invalidDiscountType
}

func intToDiscountType(i int) DiscountType {
	if i < 0 || i >= len(DiscountTypes.All()) {
		return invalidDiscountType
	}
	return DiscountTypes.All()[i]
}

func ExhaustiveDiscountTypes(f func(DiscountType)) {
	for _, p := range DiscountTypes.All() {
		f(p)
	}
}

var validDiscountTypes = map[DiscountType]bool{
	DiscountTypes.SALE:       true,
	DiscountTypes.PERCENTAGE: true,
	DiscountTypes.AMOUNT:     true,
	DiscountTypes.GIVEAWAY:   true,
}

func (p DiscountType) IsValid() bool {
	return validDiscountTypes[p]
}

func (p DiscountType) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *DiscountType) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, `"`), ` `)
	newp, err := ParseDiscountType(b)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p *DiscountType) Scan(value any) error {
	newp, err := ParseDiscountType(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p DiscountType) Value() (driver.Value, error) {
	return p.String(), nil
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [1]struct{}
	_ = x[sale-1]
	_ = x[percentage-2]
	_ = x[amount-3]
	_ = x[giveaway-4]
}

const _discounttypes_name = "salepercentageamountgiveaway"

var _discounttypes_index = [...]uint16{0, 0, 4, 14, 20, 28}

func (i discountType) String() string {
	if i < 0 || i >= discountType(len(_discounttypes_index)-1) {
		return "discounttypes(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _discounttypes_name[_discounttypes_index[i]:_discounttypes_index[i+1]]
}
