// Code generated by goenums v0.3.6. DO NOT EDIT.
// This file was generated by github.com/zarldev/goenums
// using the command:
// goenums testdata/spaces/tickets.go

package spaces

import (
	"bytes"
	"database/sql/driver"
	"fmt"
	"iter"
	"strconv"
)

type TicketStatus struct {
	ticketStatus
}

type ticketstatusesContainer struct {
	UNKNOWN   TicketStatus
	PENDING   TicketStatus
	APPROVED  TicketStatus
	REJECTED  TicketStatus
	COMPLETED TicketStatus
}

var TicketStatuses = ticketstatusesContainer{
	PENDING: TicketStatus{
		ticketStatus: pending,
	},
	APPROVED: TicketStatus{
		ticketStatus: approved,
	},
	REJECTED: TicketStatus{
		ticketStatus: rejected,
	},
	COMPLETED: TicketStatus{
		ticketStatus: completed,
	},
}

var invalidTicketStatus = TicketStatus{}

func (c ticketstatusesContainer) allSlice() []TicketStatus {
	return []TicketStatus{
		c.PENDING,
		c.APPROVED,
		c.REJECTED,
		c.COMPLETED,
	}
}

// AllSlice returns all valid TicketStatus values as a slice.
// Deprecated: Use All() with Go 1.23+ range over function types instead.
func (c ticketstatusesContainer) AllSlice() []TicketStatus {
	return c.allSlice()
}

// All returns all valid TicketStatus values.
func (c ticketstatusesContainer) All() iter.Seq[TicketStatus] {
	return func(yield func(TicketStatus) bool) {
		for _, v := range c.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

func ParseTicketStatus(a any) (TicketStatus, error) {
	res := invalidTicketStatus
	switch v := a.(type) {
	case TicketStatus:
		return v, nil
	case []byte:
		res = stringToTicketStatus(string(v))
	case string:
		res = stringToTicketStatus(v)
	case fmt.Stringer:
		res = stringToTicketStatus(v.String())
	case int:
		res = intToTicketStatus(v)
	case int64:
		res = intToTicketStatus(int(v))
	case int32:
		res = intToTicketStatus(int(v))
	}
	return res, nil
}

var (
	_ticketstatusesNameMap = map[string]TicketStatus{
		"unknown":                TicketStatuses.UNKNOWN,
		"In Progress":            TicketStatuses.PENDING,
		"Fully Approved":         TicketStatuses.APPROVED,
		"Has Been Rejected":      TicketStatuses.REJECTED,
		"Successfully Completed": TicketStatuses.COMPLETED,
	}
)

func stringToTicketStatus(s string) TicketStatus {
	if v, ok := _ticketstatusesNameMap[s]; ok {
		return v
	}
	return invalidTicketStatus
}

func intToTicketStatus(i int) TicketStatus {
	if i < 0 || i >= len(TicketStatuses.allSlice()) {
		return invalidTicketStatus
	}
	return TicketStatuses.allSlice()[i]
}

func ExhaustiveTicketStatuss(f func(TicketStatus)) {
	for _, p := range TicketStatuses.allSlice() {
		f(p)
	}
}

var validTicketStatuses = map[TicketStatus]bool{
	TicketStatuses.PENDING:   true,
	TicketStatuses.APPROVED:  true,
	TicketStatuses.REJECTED:  true,
	TicketStatuses.COMPLETED: true,
}

func (p TicketStatus) IsValid() bool {
	return validTicketStatuses[p]
}

func (p TicketStatus) MarshalJSON() ([]byte, error) {
	return []byte(`"` + p.String() + `"`), nil
}

func (p *TicketStatus) UnmarshalJSON(b []byte) error {
	b = bytes.Trim(bytes.Trim(b, `"`), ` `)
	newp, err := ParseTicketStatus(b)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p *TicketStatus) Scan(value any) error {
	newp, err := ParseTicketStatus(value)
	if err != nil {
		return err
	}
	*p = newp
	return nil
}

func (p TicketStatus) Value() (driver.Value, error) {
	return p.String(), nil
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [1]struct{}
	_ = x[unknown-0]
	_ = x[pending-1]
	_ = x[approved-2]
	_ = x[rejected-3]
	_ = x[completed-4]
}

const _ticketstatuses_name = "unknownIn ProgressFully ApprovedHas Been RejectedSuccessfully Completed"

var _ticketstatuses_index = [...]uint16{0, 7, 18, 32, 49, 71}

func (i ticketStatus) String() string {
	if i < 0 || i >= ticketStatus(len(_ticketstatuses_index)-1) {
		return "ticketstatuses(" + (strconv.FormatInt(int64(i), 10) + ")")
	}
	return _ticketstatuses_name[_ticketstatuses_index[i]:_ticketstatuses_index[i+1]]
}
