# Site settings
title: goenums
description: Type-safe enum generation for Go
url: "https://zarldev.github.io/goenums"
baseurl: "/goenums"
repository: "zarldev/goenums"
version: "0.3.6"

# Build settings
markdown: kramdown
highlighter: rouge

# Rouge syntax highlighting settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: go

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Usage
    url: /usage
  - title: Features
    url: /features
    subitems:
      - title: Type Safety
        url: /features/type-safety
      - title: JSON & DB
        url: /features/json-db
      - title: Exhaustive Handling
        url: /features/exhaustive
      - title: Iterator Support
        url: /features/iterators
  - title: Examples
    url: /examples
    subitems:
      - title: Basic
        url: /examples/basic
      - title: Extended
        url: /examples/extended
      - title: Custom Strings
        url: /examples/custom-strings