# Site settings
title: goenums
description: Type-safe enum generation for Go
url: "https://zarldev.github.io/goenums"
baseurl: "/goenums"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme