// DO NOT EDIT.
// code generated by goenums v0.4.6
//
// github.com/zarldev/goenums
//
// using the command:
// goenums -f providers.go

package llmproviders

import (
	"bytes"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"math"

	"golang.org/x/exp/constraints"
)

// LLMProvider is a type that represents a single enum value.
// It combines the core information about the enum constant and it's defined fields.
type LLMProvider struct {
	llmProvider
	Vendor        string
	ContextWindow int
	SupportsTools bool
}

// llmProvidersContainer is the container for all enum values.
// It is private and should not be used directly use the public methods on the LLMProvider type.
type llmProvidersContainer struct {
	OPENAI    LLMProvider
	ANTHROPIC LLMProvider
	GOOGLE    LLMProvider
	META      LLMProvider
	MISTRAL   LLMProvider
}

// LLMProviders is a main entry point using the LLMProvider type.
// It it a container for all enum values and provides a convenient way to access all enum values and perform
// operations, with convenience methods for common use cases.
var LLMProviders = llmProvidersContainer{
	OPENAI: LLMProvider{
		llmProvider:   openai,
		Vendor:        "OpenAI",
		ContextWindow: 128000,
		SupportsTools: true,
	},
	ANTHROPIC: LLMProvider{
		llmProvider:   anthropic,
		Vendor:        "Anthropic",
		ContextWindow: 200000,
		SupportsTools: true,
	},
	GOOGLE: LLMProvider{
		llmProvider:   google,
		Vendor:        "Google",
		ContextWindow: 1000000,
		SupportsTools: true,
	},
	META: LLMProvider{
		llmProvider:   meta,
		Vendor:        "Meta",
		ContextWindow: 128000,
		SupportsTools: false,
	},
	MISTRAL: LLMProvider{
		llmProvider:   mistral,
		Vendor:        "Mistral",
		ContextWindow: 32000,
		SupportsTools: true,
	},
}

// invalidLLMProvider is an invalid sentinel value for LLMProvider
var invalidLLMProvider = LLMProvider{
	llmProvider: -1,
}

// allSlice returns a slice of all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l llmProvidersContainer) allSlice() []LLMProvider {
	return []LLMProvider{
		LLMProviders.OPENAI,
		LLMProviders.ANTHROPIC,
		LLMProviders.GOOGLE,
		LLMProviders.META,
		LLMProviders.MISTRAL,
	}
}

// All returns an iterator over all enum values.
// This method is useful for iterating over all enum values in a loop.
func (l llmProvidersContainer) All() iter.Seq[LLMProvider] {
	return func(yield func(LLMProvider) bool) {
		for _, v := range l.allSlice() {
			if !yield(v) {
				return
			}
		}
	}
}

var ErrParseLLMProvider = errors.New("invalid input provided to parse to LLMProvider")

// ParseLLMProvider parses the input value into an enum value.
// It returns the parsed enum value or an error if the input is invalid.
// It is a convenience function that can be used to parse enum values from
// various input types, such as strings, byte slices, or other enum types.
func ParseLLMProvider(input any) (LLMProvider, error) {
	switch v := input.(type) {
	case LLMProvider:
		return v, nil
	case string:
		if result := stringToLLMProvider(v); result != nil {
			return *result, nil
		}
	case fmt.Stringer:
		if result := stringToLLMProvider(v.String()); result != nil {
			return *result, nil
		}
	case []byte:
		if result := stringToLLMProvider(string(v)); result != nil {
			return *result, nil
		}
	case int:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case int8:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case int16:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case int32:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case int64:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case uint:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case uint8:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case uint16:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case uint32:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case uint64:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case float32:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	case float64:
		if result := numberToLLMProvider(v); result != nil {
			return *result, nil
		}
	default:
		return invalidLLMProvider, fmt.Errorf("invalid type %T", input)
	}
	return invalidLLMProvider, fmt.Errorf("%w: invalid value %v", ErrParseLLMProvider, input)
}

// llmProvidersNameMap is a map of enum values to their LLMProvider representation
// It is used to convert string representations of enum values into their LLMProvider representation.
var llmProvidersNameMap = map[string]LLMProvider{
	"openai":    LLMProviders.OPENAI,
	"anthropic": LLMProviders.ANTHROPIC,
	"google":    LLMProviders.GOOGLE,
	"meta":      LLMProviders.META,
	"mistral":   LLMProviders.MISTRAL,
}

// stringToLLMProvider converts a string representation of an enum value into its LLMProvider representation
// It returns a pointer to the LLMProvider representation of the enum value if the string is valid
// Otherwise, it returns nil
func stringToLLMProvider(s string) *LLMProvider {
	if t, ok := llmProvidersNameMap[s]; ok {
		return &t
	}
	return nil
}

// numberToLLMProvider converts a numeric value to a LLMProvider
// It returns a pointer to the LLMProvider representation of the enum value if the numeric value is valid
// Otherwise, it returns nil
func numberToLLMProvider[T constraints.Integer | constraints.Float](num T) *LLMProvider {
	f := float64(num)
	if math.Floor(f) != f {
		return nil
	}
	i := int(f)
	if i <= 0 || i > len(LLMProviders.allSlice()) {
		return nil
	}
	result := LLMProviders.allSlice()[i-1]
	if !result.IsValid() {
		return nil
	}
	return &result
}

// ExhaustiveLLMProviders iterates over all enum values and calls the provided function for each value.
// This function is useful for performing operations on all valid enum values in a loop.
func ExhaustiveLLMProviders(f func(LLMProvider)) {
	for _, p := range LLMProviders.allSlice() {
		f(p)
	}
}

// validLLMProviders is a map of enum values to their validity
var validLLMProviders = map[LLMProvider]bool{
	LLMProviders.OPENAI:    true,
	LLMProviders.ANTHROPIC: true,
	LLMProviders.GOOGLE:    true,
	LLMProviders.META:      true,
	LLMProviders.MISTRAL:   true,
}

// IsValid checks whether the LLMProviders value is valid.
// A valid value is one that is defined in the original enum and not marked as invalid.
func (l LLMProvider) IsValid() bool {
	return validLLMProviders[l]
}

// MarshalJSON implements the json.Marshaler interface for LLMProvider.
// It returns the JSON representation of the enum value as a byte slice.
func (l LLMProvider) MarshalJSON() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalJSON implements the json.Unmarshaler interface for LLMProvider.
// It parses the JSON representation of the enum value from the byte slice.
// It returns an error if the input is not a valid JSON representation.
func (l *LLMProvider) UnmarshalJSON(by []byte) error {
	by = bytes.Trim(bytes.Trim(by, "\""), "\"")
	newl, err := ParseLLMProvider(by)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalText implements the encoding.TextMarshaler interface for LLMProvider.
// It returns the string representation of the enum value as a byte slice
func (l LLMProvider) MarshalText() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for LLMProvider.
// It parses the string representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LLMProvider) UnmarshalText(by []byte) error {
	newl, err := ParseLLMProvider(by)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Scan implements the database/sql.Scanner interface for LLMProvider.
// It parses the string representation of the enum value from the database row.
// It returns an error if the row does not contain a valid enum value.
func (l *LLMProvider) Scan(value any) error {
	newl, err := ParseLLMProvider(value)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// Value implements the database/sql/driver.Valuer interface for LLMProvider.
// It returns the string representation of the enum value.
func (l LLMProvider) Value() (driver.Value, error) {
	return l.String(), nil
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for LLMProvider.
// It returns the binary representation of the enum value as a byte slice.
func (l LLMProvider) MarshalBinary() ([]byte, error) {
	return []byte("\"" + l.String() + "\""), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for LLMProvider.
// It parses the binary representation of the enum value from the byte slice.
// It returns an error if the byte slice does not contain a valid enum value.
func (l *LLMProvider) UnmarshalBinary(by []byte) error {
	newl, err := ParseLLMProvider(by)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// MarshalYAML implements the yaml.Marshaler interface for LLMProvider.
// It returns the string representation of the enum value.
func (l LLMProvider) MarshalYAML() ([]byte, error) {
	return []byte(l.String()), nil
}

// UnmarshalYAML implements the yaml.Unmarshaler interface for Planet.
// It parses the byte slice representation of the enum value and returns an error
// if the YAML byte slice does not contain a valid enum value.
func (l *LLMProvider) UnmarshalYAML(by []byte) error {
	newl, err := ParseLLMProvider(by)
	if err != nil {
		return err
	}
	*l = newl
	return nil
}

// llmproviderNames is a constant string slice containing all enum values cononical absolute names
const llmproviderNames = "openaianthropicgooglemetamistral"

// llmproviderNamesMap is a map of enum values to their canonical absolute
// name positions within the llmproviderNames string slice
var llmproviderNamesMap = map[LLMProvider]string{
	LLMProviders.OPENAI:    llmproviderNames[0:6],
	LLMProviders.ANTHROPIC: llmproviderNames[6:15],
	LLMProviders.GOOGLE:    llmproviderNames[15:21],
	LLMProviders.META:      llmproviderNames[21:25],
	LLMProviders.MISTRAL:   llmproviderNames[25:32],
}

// String implements the Stringer interface.
// It returns the canonical absolute name of the enum value.
func (l LLMProvider) String() string {
	if str, ok := llmproviderNamesMap[l]; ok {
		return str
	}
	return fmt.Sprintf("llmprovider(%d)", l.llmProvider)
}

// Compile-time check that all enum values are valid.
// This function is used to ensure that all enum values are defined and valid.
// It is called by the compiler to verify that the enum values are valid.
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the goenums command to generate them again.
	// Does not identify newly added constant values unless order changes
	var x [6]struct{}
	_ = x[openai-1]
	_ = x[anthropic-2]
	_ = x[google-3]
	_ = x[meta-4]
	_ = x[mistral-5]
}
